using Microsoft.AspNetCore.Mvc;
using Microsoft.SemanticKernel;
using Microsoft.SemanticKernel.ChatCompletion;
using ShoppingAssistant.Data.Requests;
using ShoppingAssistant.Services.Kernel;

namespace ShoppingAssistant.Controllers;

/// <summary>
/// Represents an API controller that processes user messages and generates responses using the shopping assistant AI.
/// </summary>
/// <remarks>This controller provides endpoints for interacting with the shopping assistant, leveraging AI
/// services to generate responses based on user input. It is intended to be used as part of an ASP.NET Core application
/// and is configured with the necessary AI kernel, prompt loader, and chat completion service dependencies.</remarks>
[ApiController]
[Route("assistant")]
public sealed class AssistantController : ControllerBase
{
    private readonly Kernel _kernel;
    private readonly PromptLoader _promptLoader;
    private readonly IChatCompletionService _chatCompletionService;

    /// <summary>
    /// Initializes a new instance of the AssistantController class with the specified kernel, prompt loader, and chat
    /// completion service.
    /// </summary>
    /// <param name="kernel">The kernel instance used to manage and execute AI operations.</param>
    /// <param name="promptLoader">The prompt loader responsible for retrieving and managing prompt templates.</param>
    /// <param name="chatCompletionService">The chat completion service used to generate AI responses for chat interactions.</param>
    public AssistantController(
        Kernel kernel,
        PromptLoader promptLoader,
        IChatCompletionService chatCompletionService)
    {
        this._kernel = kernel;
        this._promptLoader = promptLoader;
        this._chatCompletionService = this._kernel.GetRequiredService<IChatCompletionService>();
    }

    /// <summary>
    /// Processes a user message and returns a response generated by the shopping assistant AI.
    /// </summary>
    /// <remarks>This endpoint expects a JSON payload with the user's message in the request body. The
    /// response includes the AI-generated answer in a JSON object with an 'answer' property.</remarks>
    /// <param name="request">The user message to process. Must contain the text of the user's query.</param>
    /// <returns>An <see cref="IActionResult"/> containing the AI-generated answer to the user's message.</returns>
    [HttpPost]
    public async Task<IActionResult> AskAsync([FromBody] UserMessage request)
    {
        var history = new ChatHistory();
        history.AddUserMessage(request.Message);

        KernelFunction function = this._promptLoader.GetShoppingAssistantPrompt();

        FunctionResult result = await this._kernel.InvokeAsync(function, new()
        {
            { "input", request.Message }
        });

        return Ok(new
        {
            answer = result.ToString()
        });
    }
}
