namespace ShoppingAssistant.Models.Enumerators;

#pragma warning disable CS1591

/// <summary>
/// Specifies the available categories for classification or grouping within the application.
/// </summary>
public enum Category
{
    // Electronics and gadgets
    Electronics,
    Computers,
    Laptops,
    Desktops,
    Tablets,
    Smartphones,
    Wearables,
    Cameras,
    DSLR,
    Mirrorless,
    ActionCameras,
    Audio,
    Headphones,
    Earbuds,
    Speakers,
    HomeAudio,
    Televisions,
    SmartTVs,
    Projectors,
    GamingConsoles,
    GamingAccessories,
    Software,
    SmartHome,
    HomeAutomation,
    Networking,
    Routers,
    StorageDevices,
    MemoryCards,
    Batteries,
    Chargers,

    // Household and furniture
    Furniture,
    Bedroom,
    Beds,
    Mattresses,
    Wardrobes,
    LivingRoom,
    Sofas,
    CoffeeTables,
    TVStands,
    Office,
    Desks,
    Chairs,
    Bookcases,
    Lighting,
    CeilingLights,
    Lamps,
    WallLights,
    Decor,
    Rugs,
    Curtains,
    Mirrors,
    Clocks,

    // Clouthing and fashion
    Clothing,
    MenClothing,
    Shirts,
    Pants,
    Jackets,
    Suits,
    WomenClothing,
    Dresses,
    Skirts,
    Blouses,
    Coats,
    KidsClothing,
    BabyClothes,
    Shoes,
    Sneakers,
    Boots,
    Sandals,
    Accessories,
    Belts,
    Hats,
    Scarves,
    Bags,
    Backpacks,
    Handbags,
    Wallets,
    Jewelry,
    Necklaces,
    Bracelets,
    Rings,
    Watches,

    // Appearance and personal care
    Beauty,
    Skincare,
    Moisturizers,
    Cleansers,
    Serums,
    Haircare,
    Shampoos,
    Conditioners,
    HairTools,
    Makeup,
    Lipstick,
    Eyeshadow,
    Foundation,
    Fragrances,
    Perfumes,
    Deodorants,
    Health,
    Vitamins,
    Supplements,
    PersonalCare,
    OralCare,
    DentalHygiene,
    FirstAid,

    // Sport and outdoor activities
    Sports,
    FitnessEquipment,
    Treadmills,
    Dumbbells,
    YogaMats,
    Outdoor,
    Bicycles,
    MountainBikes,
    RoadBikes,
    CampingGear,
    Tents,
    SleepingBags,
    HikingGear,
    ClimbingGear,
    WaterSports,
    Surfboards,
    Kayaks,
    WinterSports,
    Skis,
    Snowboards,
    Running,
    Apparel,

    // Toys and games
    Toys,
    BoardGames,
    Puzzles,
    EducationalToys,
    Dolls,
    ActionFigures,
    VideoGames,
    ConsoleGames,
    PCGames,
    GameControllers,
    VRGear,

    // Books and articles
    Books,
    Fiction,
    NonFiction,
    Comics,
    GraphicNovels,
    Textbooks,
    Stationery,
    Pens,
    Notebooks,
    OfficeSupplies,

    // Animals and pet products
    PetSupplies,
    DogFood,
    CatFood,
    PetToys,
    PetBeds,
    PetGrooming,

    // Food and beverages
    Grocery,
    Beverages,
    Coffee,
    Tea,
    Juice,
    Snacks,
    Chips,
    Chocolate,
    Candy,
    BabyFood,

    // Moto and tools
    Automotive,
    CarAccessories,
    MotorcycleAccessories,
    Tools,
    PowerTools,
    HandTools,
    Garden,
    GardeningTools,
    Seeds,
    Plants,
    OutdoorFurniture,

    // Music and arts
    MusicInstruments,
    Guitars,
    Keyboards,
    Drums,
    MusicalAccessories,
    SheetMusic,
    ArtSupplies,
    Paints,
    Brushes,
    Canvas,
    Crafts,
    DIYKits,
    Collectibles,

    // Journey and outdoor gear
    Travel,
    Luggage,
    Suitcases,
    TravelAccessories,
    NeckPillows,
    PassportHolders,

    // Health and safety products
    SafetyEquipment,
    Helmets,
    ProtectiveGear,
    MedicalSupplies,
    FirstAidKits,
    Masks,
    Gloves,

    // Seasonal and holiday items
    Seasonal,
    Christmas,
    Halloween,
    Easter,
    PartySupplies,
    Decorations,
    Balloons,
    Tableware,

    // Eco-friendly and sustainable products
    EcoFriendly,
    ReusableBags,
    SolarProducts,
    BiodegradableProducts,
    RecyclingProducts,

    // Additional Categories
    BabyProducts,
    Diapers,
    Strollers,
    CarSeats,
    EducationTech,
    ECommerceTools,
    Startups,
    Innovation,
    Leadership,
    SelfImprovement,
    Productivity,
    Entrepreneurship,
    Philosophy,
    Psychology,
    Law,
    Ethics,
    ClimateChange,
    Conservation,
    SpaceExploration,
    RenewableEnergy
}

#pragma warning restore CS1591